//! JSBSim comparison fixture.
//!
//! Compares avian_fdm's J3Cub against pre-recorded JSBSim reference data
//! (`tests/fixtures/jsbsim_j3cub_60s.csv`). The reference file is committed
//! to the repository and was generated by `tests/run_jsbsim.py`.
//!
//! ## Tests
//!
//! * **`jsbsim_j3cub_comparison`** — always runs (with `--features presets`).
//!   Loads the committed CSV, runs avian_fdm headlessly, and prints a
//!   side-by-side comparison table.
//!
//! * **`jsbsim_regenerate_reference`** — runs only when `JSBSIM_DATA_PATH` is
//!   set.  Re-runs the Python JSBSim script and asserts that the output matches
//!   the committed CSV (guards against accidental staleness).
//!
//! ## Regenerating reference data
//!
//! ```sh
//! # 1. Install JSBSim in a venv (one-time setup)
//! python3 -m venv .venv && .venv/bin/pip install jsbsim
//!
//! # 2. Regenerate the CSV
//! JSBSIM_DATA_PATH=../jsbsim .venv/bin/python3 tests/run_jsbsim.py \
//!     2>/dev/null | grep -E '^[0-9t]' > tests/fixtures/jsbsim_j3cub_60s.csv
//! ```

#![cfg(feature = "presets")]

use std::time::Duration;

use avian3d::prelude::*;
use avian_fdm::prelude::*;
use avian_fdm::presets::j3cub;
use bevy::prelude::*;
use bevy::time::TimeUpdateStrategy;

// ── Configuration ────────────────────────────────────────────────────────────

const SIM_DURATION_S: f64 = 60.0;
const SAMPLE_INTERVAL_S: f64 = 0.5;
const PHYSICS_DT: f64 = 1.0 / 60.0;
const TOTAL_FRAMES: usize = (SIM_DURATION_S / PHYSICS_DT) as usize + 1;

/// Reference CSV file, committed alongside the test.
const REFERENCE_CSV: &str = include_str!("fixtures/jsbsim_j3cub_60s.csv");

/// Target tolerances (post-calibration).  Currently the models diverge
/// significantly; see comparison output for details.
const _TARGET_ALT_PCT: f64 = 1.0;
const _TARGET_TAS_PCT: f64 = 1.0;
const _TARGET_AOA_DEG: f64 = 1.0;

// ── Sample type ──────────────────────────────────────────────────────────────

#[derive(Debug, Clone)]
struct Sample {
    time: f64,
    altitude_m: f64,
    airspeed_ms: f64,
    alpha_deg: f64,
}

// ── CSV parsing ──────────────────────────────────────────────────────────────

fn parse_csv(csv: &str) -> Vec<Sample> {
    let mut samples = Vec::new();
    for line in csv.lines() {
        let p: Vec<&str> = line.split(',').collect();
        if p.len() != 4 {
            continue;
        }
        let Ok(time) = p[0].parse::<f64>() else {
            continue;
        };
        let (Ok(alt), Ok(tas), Ok(aoa)) = (
            p[1].parse::<f64>(),
            p[2].parse::<f64>(),
            p[3].parse::<f64>(),
        ) else {
            continue;
        };
        samples.push(Sample {
            time,
            altitude_m: alt,
            airspeed_ms: tas,
            alpha_deg: aoa,
        });
    }
    samples
}

// ── avian_fdm runner (embedded Bevy app) ─────────────────────────────────────

#[derive(Resource)]
struct SampleCollector {
    samples: Vec<Sample>,
    next_sample_time: f64,
}

impl Default for SampleCollector {
    fn default() -> Self {
        Self {
            samples: Vec::new(),
            next_sample_time: SAMPLE_INTERVAL_S,
        }
    }
}

fn spawn_aircraft(mut commands: Commands) {
    let level = Quat::from_rotation_x(std::f32::consts::FRAC_PI_2);
    let root = j3cub::spawn(
        &mut commands,
        Transform::from_xyz(0.0, 300.0, 0.0).with_rotation(level),
    );
    commands
        .entity(root)
        .insert(LinearVelocity(Vec3::new(27.0, 0.0, 0.0)));
}

fn ramp_throttle(mut query: Query<&mut ControlInputs, With<AircraftGeometry>>, time: Res<Time>) {
    let t = time.elapsed_secs_f64();
    let throttle = (0.5 + t / 50.0).min(0.75);
    for mut ctrl in &mut query {
        ctrl.throttle = throttle;
    }
}

fn collect_samples(
    query: Query<&FlightState, With<AircraftGeometry>>,
    time: Res<Time>,
    mut collector: ResMut<SampleCollector>,
) {
    let t = time.elapsed_secs_f64();
    if t < collector.next_sample_time {
        return;
    }
    collector.next_sample_time += SAMPLE_INTERVAL_S;

    for state in &query {
        collector.samples.push(Sample {
            time: t,
            altitude_m: state.altitude_m,
            airspeed_ms: state.airspeed_ms,
            alpha_deg: state.alpha_rad.to_degrees(),
        });
    }
}

fn run_avian_fdm() -> Vec<Sample> {
    let mut app = App::new();

    app.add_plugins(MinimalPlugins)
        .add_plugins(bevy::transform::TransformPlugin)
        .add_plugins(bevy::asset::AssetPlugin::default())
        .add_plugins(PhysicsPlugins::default())
        .add_plugins(AircraftFdmPlugin);

    app.insert_resource(TimeUpdateStrategy::ManualDuration(
        Duration::from_secs_f64(PHYSICS_DT),
    ));

    app.init_resource::<SampleCollector>();
    app.add_systems(Startup, spawn_aircraft);
    app.add_systems(Update, (ramp_throttle, collect_samples));

    app.finish();

    for _ in 0..TOTAL_FRAMES {
        app.update();
    }

    app.world().resource::<SampleCollector>().samples.clone()
}

// ── Main comparison test (always runs) ───────────────────────────────────────

#[test]
fn jsbsim_j3cub_comparison() {
    // ── Load committed JSBSim reference data ─────────────────────────────
    let jsbsim_data = parse_csv(REFERENCE_CSV);
    assert!(
        jsbsim_data.len() >= 100,
        "Reference CSV has too few samples ({})",
        jsbsim_data.len()
    );

    // ── Run avian_fdm ────────────────────────────────────────────────────
    let avian_data = run_avian_fdm();
    assert!(!avian_data.is_empty(), "avian_fdm produced no samples");

    // ── Side-by-side comparison ──────────────────────────────────────────
    let n = jsbsim_data.len().min(avian_data.len());

    println!(
        "\n{:>6} │ {:>9} {:>9} {:>7} │ {:>9} {:>9} {:>7} │ {:>6} {:>6} {:>6}",
        "t(s)", "alt_js", "alt_av", "Δ%", "tas_js", "tas_av", "Δ%", "α_js", "α_av", "Δ°"
    );
    println!("{:─>100}", "");

    let mut max_alt_err = 0.0_f64;
    let mut max_tas_err = 0.0_f64;
    let mut max_aoa_err = 0.0_f64;

    for i in 0..n {
        let js = &jsbsim_data[i];
        let av = &avian_data[i];

        let alt_err =
            ((js.altitude_m - av.altitude_m) / js.altitude_m.abs().max(1.0)).abs() * 100.0;
        let tas_err =
            ((js.airspeed_ms - av.airspeed_ms) / js.airspeed_ms.abs().max(1.0)).abs() * 100.0;
        let aoa_err = (js.alpha_deg - av.alpha_deg).abs();

        max_alt_err = max_alt_err.max(alt_err);
        max_tas_err = max_tas_err.max(tas_err);
        max_aoa_err = max_aoa_err.max(aoa_err);

        println!(
            "{:6.1} │ {:9.2} {:9.2} {:+6.1}% │ {:9.2} {:9.2} {:+6.1}% │ {:+6.2} {:+6.2} {:+5.2}°",
            js.time,
            js.altitude_m, av.altitude_m, alt_err,
            js.airspeed_ms, av.airspeed_ms, tas_err,
            js.alpha_deg, av.alpha_deg, aoa_err,
        );
    }

    println!("\n── Summary ──────────────────────────────────────");
    println!("  Samples compared:   {n}");
    println!("  Max altitude error: {max_alt_err:.2}%  (target: ±{_TARGET_ALT_PCT}%)");
    println!("  Max TAS error:      {max_tas_err:.2}%  (target: ±{_TARGET_TAS_PCT}%)");
    println!("  Max AoA error:      {max_aoa_err:.2}°  (target: ±{_TARGET_AOA_DEG}°)");

    // ── Sanity assertions ────────────────────────────────────────────────
    for s in avian_data.iter() {
        assert!(
            s.altitude_m > 0.0 && s.altitude_m < 2000.0,
            "avian_fdm altitude out of range at t={:.1}s: {:.1} m",
            s.time,
            s.altitude_m,
        );
        assert!(
            s.airspeed_ms > 5.0 && s.airspeed_ms < 100.0,
            "avian_fdm TAS out of range at t={:.1}s: {:.1} m/s",
            s.time,
            s.airspeed_ms,
        );
        assert!(
            s.alpha_deg.abs() < 20.0,
            "avian_fdm AoA out of range at t={:.1}s: {:.1}°",
            s.time,
            s.alpha_deg,
        );
    }

    println!("\n  ✓ avian_fdm produced physically sane flight data.");
    println!("  ⚠ Precision tolerance matching deferred (model calibration needed).");
}

// ── Reference data freshness check (requires JSBSim) ─────────────────────────

#[test]
fn jsbsim_regenerate_reference() {
    let Ok(data_path) = std::env::var("JSBSIM_DATA_PATH") else {
        eprintln!("⏭  Skipping JSBSim regeneration check: JSBSIM_DATA_PATH not set.");
        return;
    };

    let crate_dir = std::path::Path::new(env!("CARGO_MANIFEST_DIR"));
    let script = crate_dir.join("tests").join("run_jsbsim.py");

    let venv_python = crate_dir.join(".venv").join("bin").join("python3");
    let python = if venv_python.exists() {
        venv_python.to_string_lossy().into_owned()
    } else {
        "python3".to_string()
    };

    let output = std::process::Command::new(&python)
        .arg(&script)
        .env("JSBSIM_DATA_PATH", &data_path)
        .output();

    let Ok(output) = output else {
        eprintln!("⏭  Skipping: python3 not available.");
        return;
    };

    if !output.status.success() {
        let stderr = String::from_utf8_lossy(&output.stderr);
        eprintln!("⏭  Skipping: JSBSim script failed:\n{stderr}");
        return;
    }

    let fresh_csv = String::from_utf8_lossy(&output.stdout);
    let fresh = parse_csv(&fresh_csv);
    let committed = parse_csv(REFERENCE_CSV);

    assert_eq!(
        fresh.len(),
        committed.len(),
        "Regenerated CSV has {} samples, committed has {} — re-run run_jsbsim.py",
        fresh.len(),
        committed.len(),
    );

    for (i, (f, c)) in fresh.iter().zip(committed.iter()).enumerate() {
        let alt_diff = (f.altitude_m - c.altitude_m).abs();
        let tas_diff = (f.airspeed_ms - c.airspeed_ms).abs();
        assert!(
            alt_diff < 0.01 && tas_diff < 0.01,
            "Reference CSV stale at sample {i} (t={:.1}s): alt Δ={alt_diff:.4}, TAS Δ={tas_diff:.4}. \
             Regenerate with: JSBSIM_DATA_PATH=../jsbsim .venv/bin/python3 tests/run_jsbsim.py \
             2>/dev/null | grep -E '^[0-9t]' > tests/fixtures/jsbsim_j3cub_60s.csv",
            f.time,
        );
    }

    println!("  ✓ Committed reference CSV matches fresh JSBSim run.");
}
