//! JSBSim comparison fixture.
//!
//! Compares avian_fdm's J3Cub against pre-recorded JSBSim reference data.
//! Reference files are committed to the repository and generated by the
//! Python scripts in `tests/`.
//!
//! ## Tests
//!
//! * **`jsbsim_j3cub_comparison`** — powered flight (throttle ramp 50-75%).
//!   Always runs with `--features presets`.
//!
//! * **`jsbsim_j3cub_glide_comparison`** — engine off, unpowered glide.
//!   Always runs with `--features presets`. Uses `Failure { remaining: 0.0 }`
//!   on the engine zone to exercise the damage model path.
//!
//! * **`jsbsim_regenerate_reference`** and **`jsbsim_regenerate_glide_reference`**
//!   — run only when `JSBSIM_DATA_PATH` is set. Re-run the Python JSBSim
//!   scripts and assert the output matches the committed CSVs.
//!
//! ## Regenerating reference data
//!
//! The scripts use the J3Cub FlightGear aircraft repo (Datcom aero, rev 1.26).
//! `J3CUB_AIRCRAFT_PATH` defaults to `dirname(JSBSIM_DATA_PATH)`, which works
//! when the `jsbsim` and `J3Cub` repos are siblings (e.g. both under `openskies/`).
//!
//! ```sh
//! # 1. Install JSBSim in a venv (one-time setup)
//! python3 -m venv .venv && .venv/bin/pip install jsbsim
//!
//! # 2. Powered flight
//! JSBSIM_DATA_PATH=../jsbsim .venv/bin/python3 tests/run_jsbsim.py \
//!     2>/dev/null | grep -E '^[0-9t]' > tests/fixtures/jsbsim_j3cub_60s.csv
//!
//! # 3. Glide (engine off)
//! JSBSIM_DATA_PATH=../jsbsim .venv/bin/python3 tests/run_jsbsim_glide.py \
//!     2>/dev/null | grep -E '^[0-9t]' > tests/fixtures/jsbsim_j3cub_glide_60s.csv
//! ```

use std::time::Duration;

use avian3d::math::Scalar;
use avian3d::prelude::*;
use avian_fdm::prelude::*;
use avian_fdm_j3cub_jsbsim::presets::j3cub;
use bevy::prelude::*;
use bevy::time::TimeUpdateStrategy;

// ── Configuration ────────────────────────────────────────────────────────────

const SIM_DURATION_S: f64 = 60.0;
const SAMPLE_INTERVAL_S: f64 = 0.5;
const PHYSICS_DT: f64 = 1.0 / 60.0;
const TOTAL_FRAMES: usize = (SIM_DURATION_S / PHYSICS_DT) as usize + 1;

/// Reference CSV file, committed alongside the test.
const REFERENCE_CSV: &str = include_str!("fixtures/jsbsim_j3cub_60s.csv");

/// Reference CSV for unpowered glide (engine off).
const REFERENCE_CSV_GLIDE: &str = include_str!("fixtures/jsbsim_j3cub_glide_60s.csv");

/// Target tolerances (post-calibration).  Currently the models diverge
/// significantly; see comparison output for details.
const _TARGET_ALT_PCT: f64 = 1.0;
const _TARGET_TAS_PCT: f64 = 1.0;
const _TARGET_AOA_DEG: f64 = 1.0;

// ── Sample type ──────────────────────────────────────────────────────────────

#[derive(Debug, Clone)]
struct Sample {
    time: f64,
    altitude_m: f64,
    airspeed_ms: f64,
    alpha_deg: f64,
}

// ── CSV parsing ──────────────────────────────────────────────────────────────

fn parse_csv(csv: &str) -> Vec<Sample> {
    let mut samples = Vec::new();
    for line in csv.lines() {
        let p: Vec<&str> = line.split(',').collect();
        if p.len() != 4 {
            continue;
        }
        let Ok(time) = p[0].parse::<f64>() else {
            continue;
        };
        let (Ok(alt), Ok(tas), Ok(aoa)) = (
            p[1].parse::<f64>(),
            p[2].parse::<f64>(),
            p[3].parse::<f64>(),
        ) else {
            continue;
        };
        samples.push(Sample {
            time,
            altitude_m: alt,
            airspeed_ms: tas,
            alpha_deg: aoa,
        });
    }
    samples
}

// ── avian_fdm runner (embedded Bevy app) ─────────────────────────────────────

#[derive(Resource)]
struct SampleCollector {
    samples: Vec<Sample>,
    next_sample_time: f64,
}

impl Default for SampleCollector {
    fn default() -> Self {
        Self {
            samples: Vec::new(),
            next_sample_time: SAMPLE_INTERVAL_S,
        }
    }
}

fn spawn_aircraft(mut commands: Commands) {
    // Match JSBSim initial conditions: ic/theta-rad = 0.0 (level), vt = 27 m/s.
    // JSBSim does not pre-pitch - it starts level and converges to trim AoA within
    // the first few steps. See tests/run_jsbsim.py for the reference conditions.
    let initial_rot = Quat::from_rotation_x(std::f32::consts::FRAC_PI_2);
    let root = j3cub::spawn(
        &mut commands,
        Transform::from_xyz(0.0, 300.0, 0.0).with_rotation(initial_rot),
    );
    commands
        .entity(root)
        .insert(LinearVelocity(Vec3::new(27.0, 0.0, 0.0)));
}

#[allow(clippy::unnecessary_cast)]
fn ramp_throttle(mut query: Query<&mut ControlInputs, With<AircraftGeometry>>, time: Res<Time>) {
    let t = time.elapsed_secs_f64();
    let throttle = (0.5 + t / 50.0).min(0.75) as Scalar;
    for mut ctrl in &mut query {
        ctrl.throttle = throttle;
    }
}

fn collect_samples(
    query: Query<&FlightState, With<AircraftGeometry>>,
    time: Res<Time>,
    mut collector: ResMut<SampleCollector>,
) {
    let t = time.elapsed_secs_f64();
    if t < collector.next_sample_time {
        return;
    }
    collector.next_sample_time += SAMPLE_INTERVAL_S;

    for state in &query {
        collector.samples.push(Sample {
            time: t,
            #[allow(clippy::unnecessary_cast)]
            altitude_m: state.altitude_m as f64,
            #[allow(clippy::unnecessary_cast)]
            airspeed_ms: state.airspeed_ms as f64,
            #[allow(clippy::unnecessary_cast)]
            alpha_deg: state.alpha_rad.to_degrees() as f64,
        });
    }
}

fn run_avian_fdm() -> Vec<Sample> {
    let mut app = App::new();

    app.add_plugins(MinimalPlugins)
        .add_plugins(bevy::transform::TransformPlugin)
        .add_plugins(bevy::asset::AssetPlugin::default())
        .add_plugins(PhysicsPlugins::default())
        .add_plugins(AircraftFdmPlugin::default());

    app.insert_resource(TimeUpdateStrategy::ManualDuration(Duration::from_secs_f64(
        PHYSICS_DT,
    )));

    app.init_resource::<SampleCollector>();
    app.add_systems(Startup, spawn_aircraft);
    app.add_systems(Update, (ramp_throttle, collect_samples));

    app.finish();

    for _ in 0..TOTAL_FRAMES {
        app.update();
    }

    app.world().resource::<SampleCollector>().samples.clone()
}

// ── Main comparison test (always runs) ───────────────────────────────────────

#[test]
fn jsbsim_j3cub_comparison() {
    // ── Load committed JSBSim reference data ─────────────────────────────
    let jsbsim_data = parse_csv(REFERENCE_CSV);
    assert!(
        jsbsim_data.len() >= 100,
        "Reference CSV has too few samples ({})",
        jsbsim_data.len()
    );

    // ── Run avian_fdm ────────────────────────────────────────────────────
    let avian_data = run_avian_fdm();
    assert!(!avian_data.is_empty(), "avian_fdm produced no samples");

    // ── Side-by-side comparison ──────────────────────────────────────────
    let n = jsbsim_data.len().min(avian_data.len());

    println!(
        "\n{:>6} │ {:>9} {:>9} {:>7} │ {:>9} {:>9} {:>7} │ {:>6} {:>6} {:>6}",
        "t(s)", "alt_js", "alt_av", "Δ%", "tas_js", "tas_av", "Δ%", "α_js", "α_av", "Δ°"
    );
    println!("{:─>100}", "");

    let mut max_alt_err = 0.0_f64;
    let mut max_tas_err = 0.0_f64;
    let mut max_aoa_err = 0.0_f64;

    for i in 0..n {
        let js = &jsbsim_data[i];
        let av = &avian_data[i];

        let alt_err =
            ((js.altitude_m - av.altitude_m) / js.altitude_m.abs().max(1.0)).abs() * 100.0;
        let tas_err =
            ((js.airspeed_ms - av.airspeed_ms) / js.airspeed_ms.abs().max(1.0)).abs() * 100.0;
        let aoa_err = (js.alpha_deg - av.alpha_deg).abs();

        max_alt_err = max_alt_err.max(alt_err);
        max_tas_err = max_tas_err.max(tas_err);
        max_aoa_err = max_aoa_err.max(aoa_err);

        println!(
            "{:6.1} │ {:9.2} {:9.2} {:+6.1}% │ {:9.2} {:9.2} {:+6.1}% │ {:+6.2} {:+6.2} {:+5.2}°",
            js.time,
            js.altitude_m,
            av.altitude_m,
            alt_err,
            js.airspeed_ms,
            av.airspeed_ms,
            tas_err,
            js.alpha_deg,
            av.alpha_deg,
            aoa_err,
        );
    }

    println!("\n── Summary ──────────────────────────────────────");
    println!("  Samples compared:   {n}");
    println!("  Max altitude error: {max_alt_err:.2}%  (target: ±{_TARGET_ALT_PCT}%)");
    println!("  Max TAS error:      {max_tas_err:.2}%  (target: ±{_TARGET_TAS_PCT}%)");
    println!("  Max AoA error:      {max_aoa_err:.2}°  (target: ±{_TARGET_AOA_DEG}°)");

    // ── Sanity assertions ────────────────────────────────────────────────
    for s in avian_data.iter() {
        assert!(
            s.altitude_m > 0.0 && s.altitude_m < 2000.0,
            "avian_fdm altitude out of range at t={:.1}s: {:.1} m",
            s.time,
            s.altitude_m,
        );
        assert!(
            s.airspeed_ms > 5.0 && s.airspeed_ms < 100.0,
            "avian_fdm TAS out of range at t={:.1}s: {:.1} m/s",
            s.time,
            s.airspeed_ms,
        );
        assert!(
            s.alpha_deg.abs() < 20.0,
            "avian_fdm AoA out of range at t={:.1}s: {:.1}°",
            s.time,
            s.alpha_deg,
        );
    }

    println!("\n  ✓ avian_fdm produced physically sane flight data.");
    println!("  ⚠ Precision tolerance matching deferred (model calibration needed).");
}

// ── Glide runner (engine disabled via Failure) ───────────────────────────────

fn disable_engine(mut commands: Commands, query: Query<Entity, With<EngineZone>>) {
    for entity in &query {
        commands.entity(entity).insert(Failure { remaining: 0.0 });
    }
}

fn run_avian_fdm_glide() -> Vec<Sample> {
    let mut app = App::new();

    app.add_plugins(MinimalPlugins)
        .add_plugins(bevy::transform::TransformPlugin)
        .add_plugins(bevy::asset::AssetPlugin::default())
        .add_plugins(PhysicsPlugins::default())
        .add_plugins(AircraftFdmPlugin::default());

    app.insert_resource(TimeUpdateStrategy::ManualDuration(Duration::from_secs_f64(
        PHYSICS_DT,
    )));

    app.init_resource::<SampleCollector>();
    app.add_systems(Startup, (spawn_aircraft, disable_engine).chain());
    app.add_systems(Update, collect_samples);

    app.finish();

    for _ in 0..TOTAL_FRAMES {
        app.update();
    }

    app.world().resource::<SampleCollector>().samples.clone()
}

// ── Glide comparison test ─────────────────────────────────────────────────────

#[test]
fn jsbsim_j3cub_glide_comparison() {
    let jsbsim_data = parse_csv(REFERENCE_CSV_GLIDE);
    assert!(
        jsbsim_data.len() >= 100,
        "Glide reference CSV has too few samples ({})",
        jsbsim_data.len()
    );

    let avian_data = run_avian_fdm_glide();
    assert!(
        !avian_data.is_empty(),
        "avian_fdm glide produced no samples"
    );

    let n = jsbsim_data.len().min(avian_data.len());

    println!(
        "\n=== Glide comparison (engine off) ===\n\
         {:>6} | {:>9} {:>9} {:>7} | {:>9} {:>9} {:>7} | {:>6} {:>6} {:>6}",
        "t(s)", "alt_js", "alt_av", "d%", "tas_js", "tas_av", "d%", "a_js", "a_av", "da"
    );
    println!("{:->100}", "");

    let mut max_alt_err = 0.0_f64;
    let mut max_tas_err = 0.0_f64;
    let mut max_aoa_err = 0.0_f64;

    for i in 0..n {
        let js = &jsbsim_data[i];
        let av = &avian_data[i];

        let alt_err =
            ((js.altitude_m - av.altitude_m) / js.altitude_m.abs().max(1.0)).abs() * 100.0;
        let tas_err =
            ((js.airspeed_ms - av.airspeed_ms) / js.airspeed_ms.abs().max(1.0)).abs() * 100.0;
        let aoa_err = (js.alpha_deg - av.alpha_deg).abs();

        max_alt_err = max_alt_err.max(alt_err);
        max_tas_err = max_tas_err.max(tas_err);
        max_aoa_err = max_aoa_err.max(aoa_err);

        println!(
            "{:6.1} | {:9.2} {:9.2} {:+6.1}% | {:9.2} {:9.2} {:+6.1}% | {:+6.2} {:+6.2} {:+5.2}",
            js.time,
            js.altitude_m,
            av.altitude_m,
            alt_err,
            js.airspeed_ms,
            av.airspeed_ms,
            tas_err,
            js.alpha_deg,
            av.alpha_deg,
            aoa_err,
        );
    }

    println!("\n-- Glide summary -------------------------------------------");
    println!("  Samples compared:   {n}");
    println!("  Max altitude error: {max_alt_err:.2}%  (target: +-{_TARGET_ALT_PCT}%)");
    println!("  Max TAS error:      {max_tas_err:.2}%  (target: +-{_TARGET_TAS_PCT}%)");
    println!("  Max AoA error:      {max_aoa_err:.2} deg  (target: +-{_TARGET_AOA_DEG} deg)");

    let final_js = &jsbsim_data[n - 1];
    let final_av = &avian_data[n - 1];
    assert!(
        final_av.altitude_m > 50.0 && final_av.altitude_m < final_js.altitude_m * 1.5 + 50.0,
        "avian_fdm glide altitude unrealistic at t=60s: {:.1} m (JSBSim: {:.1} m)",
        final_av.altitude_m,
        final_js.altitude_m,
    );
    assert!(
        final_av.airspeed_ms > 10.0 && final_av.airspeed_ms < 80.0,
        "avian_fdm glide TAS out of range at t=60s: {:.1} m/s",
        final_av.airspeed_ms,
    );

    println!("  Glide comparison complete.");
}

// ── Glide reference freshness check (requires JSBSim) ────────────────────────

#[test]
fn jsbsim_regenerate_glide_reference() {
    let Ok(data_path) = std::env::var("JSBSIM_DATA_PATH") else {
        eprintln!("Skipping JSBSim glide regeneration: JSBSIM_DATA_PATH not set.");
        return;
    };

    let crate_dir = std::path::Path::new(env!("CARGO_MANIFEST_DIR"));
    let script = crate_dir.join("tests").join("run_jsbsim_glide.py");

    let venv_python = crate_dir.join(".venv").join("bin").join("python3");
    let python = if venv_python.exists() {
        venv_python.to_string_lossy().into_owned()
    } else {
        "python3".to_string()
    };

    let output = std::process::Command::new(&python)
        .arg(&script)
        .env("JSBSIM_DATA_PATH", &data_path)
        .envs(
            std::env::var("J3CUB_AIRCRAFT_PATH")
                .ok()
                .map(|v| ("J3CUB_AIRCRAFT_PATH", v)),
        )
        .output();

    let Ok(output) = output else {
        eprintln!("Skipping: python3 not available.");
        return;
    };

    if !output.status.success() {
        let stderr = String::from_utf8_lossy(&output.stderr);
        eprintln!("Skipping: JSBSim glide script failed:\n{stderr}");
        return;
    }

    let fresh_csv = String::from_utf8_lossy(&output.stdout);
    let fresh = parse_csv(&fresh_csv);
    let committed = parse_csv(REFERENCE_CSV_GLIDE);

    assert_eq!(
        fresh.len(),
        committed.len(),
        "Regenerated glide CSV has {} samples, committed has {} - re-run run_jsbsim_glide.py",
        fresh.len(),
        committed.len(),
    );

    for (i, (f, c)) in fresh.iter().zip(committed.iter()).enumerate() {
        let alt_diff = (f.altitude_m - c.altitude_m).abs();
        let tas_diff = (f.airspeed_ms - c.airspeed_ms).abs();
        assert!(
            alt_diff < 0.01 && tas_diff < 0.01,
            "Glide reference CSV stale at sample {i} (t={:.1}s): alt d={alt_diff:.4}, TAS d={tas_diff:.4}. \
             Regenerate with: JSBSIM_DATA_PATH=../jsbsim .venv/bin/python3 tests/run_jsbsim_glide.py \
             2>/dev/null | grep -E '^[0-9t]' > tests/fixtures/jsbsim_j3cub_glide_60s.csv",
            f.time,
        );
    }

    println!("  Glide reference CSV matches fresh JSBSim run.");
}

#[test]
fn jsbsim_regenerate_reference() {
    let Ok(data_path) = std::env::var("JSBSIM_DATA_PATH") else {
        eprintln!("⏭  Skipping JSBSim regeneration check: JSBSIM_DATA_PATH not set.");
        return;
    };

    let crate_dir = std::path::Path::new(env!("CARGO_MANIFEST_DIR"));
    let script = crate_dir.join("tests").join("run_jsbsim.py");

    let venv_python = crate_dir.join(".venv").join("bin").join("python3");
    let python = if venv_python.exists() {
        venv_python.to_string_lossy().into_owned()
    } else {
        "python3".to_string()
    };

    let output = std::process::Command::new(&python)
        .arg(&script)
        .env("JSBSIM_DATA_PATH", &data_path)
        .envs(
            std::env::var("J3CUB_AIRCRAFT_PATH")
                .ok()
                .map(|v| ("J3CUB_AIRCRAFT_PATH", v)),
        )
        .output();

    let Ok(output) = output else {
        eprintln!("⏭  Skipping: python3 not available.");
        return;
    };

    if !output.status.success() {
        let stderr = String::from_utf8_lossy(&output.stderr);
        eprintln!("⏭  Skipping: JSBSim script failed:\n{stderr}");
        return;
    }

    let fresh_csv = String::from_utf8_lossy(&output.stdout);
    let fresh = parse_csv(&fresh_csv);
    let committed = parse_csv(REFERENCE_CSV);

    assert_eq!(
        fresh.len(),
        committed.len(),
        "Regenerated CSV has {} samples, committed has {} — re-run run_jsbsim.py",
        fresh.len(),
        committed.len(),
    );

    for (i, (f, c)) in fresh.iter().zip(committed.iter()).enumerate() {
        let alt_diff = (f.altitude_m - c.altitude_m).abs();
        let tas_diff = (f.airspeed_ms - c.airspeed_ms).abs();
        assert!(
            alt_diff < 0.01 && tas_diff < 0.01,
            "Reference CSV stale at sample {i} (t={:.1}s): alt Δ={alt_diff:.4}, TAS Δ={tas_diff:.4}. \
             Regenerate with: JSBSIM_DATA_PATH=../jsbsim .venv/bin/python3 tests/run_jsbsim.py \
             2>/dev/null | grep -E '^[0-9t]' > tests/fixtures/jsbsim_j3cub_60s.csv",
            f.time,
        );
    }

    println!("  ✓ Committed reference CSV matches fresh JSBSim run.");
}

// ── Inertia tensor verification ──────────────────────────────────────────────

/// JSBSim J3 Cub inertia values (slug*ft2 converted to kg*m2).
///
/// Source: J3Cub.xml mass_balance section.
///   Ixx = 538.01 slug*ft2 = 729.4 kg*m2
///   Iyy = 386.81 slug*ft2 = 524.4 kg*m2
///   Izz = 871.03 slug*ft2 = 1181.0 kg*m2
///   Mass = 902.22 lb = 409.2 kg
const JSBSIM_IXX: f64 = 538.01 * 1.35582;
const JSBSIM_IYY: f64 = 386.81 * 1.35582;
const JSBSIM_IZZ: f64 = 871.03 * 1.35582;
const JSBSIM_MASS_KG: f64 = 902.22 * 0.453592;

/// Verify that Avian's auto-computed mass properties from J3 Cub zone
/// colliders are in the right ballpark compared to JSBSim.
///
/// This test spawns the aircraft, runs a few frames for Avian to compute
/// mass properties, and prints the comparison. The current collider layout
/// is a simplified approximation (cuboids), so we allow generous tolerances
/// and primarily use this for visibility rather than hard pass/fail.
#[test]
fn j3cub_inertia_comparison() {
    let mut app = App::new();

    app.add_plugins(MinimalPlugins)
        .add_plugins(bevy::transform::TransformPlugin)
        .add_plugins(bevy::asset::AssetPlugin::default())
        .add_plugins(PhysicsPlugins::default())
        .add_plugins(AircraftFdmPlugin::default());

    app.insert_resource(TimeUpdateStrategy::ManualDuration(Duration::from_secs_f64(
        1.0 / 60.0,
    )));

    app.add_systems(Startup, |mut commands: Commands| {
        let initial_rot = Quat::from_rotation_x(std::f32::consts::FRAC_PI_2);
        j3cub::spawn(
            &mut commands,
            Transform::from_xyz(0.0, 300.0, 0.0).with_rotation(initial_rot),
        );
    });

    app.finish();

    // Run a few frames so Avian computes mass properties from colliders.
    for _ in 0..5 {
        app.update();
    }

    // Read computed mass properties.
    let mut found = false;
    let world = app.world_mut();
    let mut query = world.query::<(
        &ComputedMass,
        &ComputedAngularInertia,
        &ComputedCenterOfMass,
    )>();

    for (mass, inertia, com) in query.iter(&world) {
        found = true;
        let m = mass.value() as f64;
        let (principal, local_frame) = inertia.principal_angular_inertia_with_local_frame();

        // Reconstruct body-frame inertia tensor from principal axes + rotation.
        // I_body = R * diag(principal) * R^T
        let r = bevy::math::Mat3::from_quat(local_frame);
        let p = [principal.x as f64, principal.y as f64, principal.z as f64];
        let mut ib = [[0.0f64; 3]; 3];
        for i in 0..3 {
            for j in 0..3 {
                for k in 0..3 {
                    let ri = [r.x_axis[i] as f64, r.y_axis[i] as f64, r.z_axis[i] as f64];
                    let rj = [r.x_axis[j] as f64, r.y_axis[j] as f64, r.z_axis[j] as f64];
                    ib[i][j] += ri[k] * p[k] * rj[k];
                }
            }
        }
        let ixx = ib[0][0];
        let iyy = ib[1][1];
        let izz = ib[2][2];

        println!("\n-- J3 Cub Inertia Comparison (body frame) -------------------");
        println!(
            "  {:>20} {:>10} {:>10} {:>8}",
            "", "Avian", "JSBSim", "Ratio"
        );
        println!(
            "  {:>20} {:10.1} {:10.1} {:8.2}",
            "Mass (kg)",
            m,
            JSBSIM_MASS_KG,
            m / JSBSIM_MASS_KG
        );
        println!(
            "  {:>20} {:10.1} {:10.1} {:8.2}",
            "Ixx (kg*m2)",
            ixx,
            JSBSIM_IXX,
            ixx / JSBSIM_IXX
        );
        println!(
            "  {:>20} {:10.1} {:10.1} {:8.2}",
            "Iyy (kg*m2)",
            iyy,
            JSBSIM_IYY,
            iyy / JSBSIM_IYY
        );
        println!(
            "  {:>20} {:10.1} {:10.1} {:8.2}",
            "Izz (kg*m2)",
            izz,
            JSBSIM_IZZ,
            izz / JSBSIM_IZZ
        );
        println!("  {:>20} {:?}", "CG offset (m)", com.0);
        println!("------------------------------------------------------------");

        // Mass within 5%
        let mass_ratio = m / JSBSIM_MASS_KG;
        assert!(
            mass_ratio > 0.95 && mass_ratio < 1.05,
            "Mass off: {m:.1} kg (target: {JSBSIM_MASS_KG:.1} kg, ratio: {mass_ratio:.2})"
        );
        // Inertia within 15% (body-frame, after rotation)
        let ixx_ratio = ixx / JSBSIM_IXX;
        let iyy_ratio = iyy / JSBSIM_IYY;
        let izz_ratio = izz / JSBSIM_IZZ;
        assert!(
            ixx_ratio > 0.85 && ixx_ratio < 1.15,
            "Ixx off: {ixx:.0} (target: {JSBSIM_IXX:.0}, ratio: {ixx_ratio:.2})"
        );
        assert!(
            iyy_ratio > 0.85 && iyy_ratio < 1.15,
            "Iyy off: {iyy:.0} (target: {JSBSIM_IYY:.0}, ratio: {iyy_ratio:.2})"
        );
        assert!(
            izz_ratio > 0.85 && izz_ratio < 1.15,
            "Izz off: {izz:.0} (target: {JSBSIM_IZZ:.0}, ratio: {izz_ratio:.2})"
        );
    }

    assert!(found, "No aircraft entity found with mass properties");
}

// ── Emergent pitch-damping measurement ───────────────────────────────────────

/// Measure emergent Cmq by comparing the aero pitch torque at zero vs
/// non-zero pitch rate. The delta isolates the pitch-rate-dependent
/// contribution.
///
/// The J3 Cub does not use LodDamping. Pitch damping emerges from
/// per-zone local-angle corrections: `delta_alpha = -q * x / V` at each
/// zone, which increases h-stab alpha during pitch-up, producing a
/// nose-down restoring moment.
///
/// Datcom target: Cmq = -6/rad.
/// Expected emergent: Cmq ~ -10/rad (no downwash lag).
#[test]
fn j3cub_emergent_cmq() {
    fn build_app(pitch_rate_world_z: f32) -> App {
        let mut app = App::new();
        app.add_plugins(MinimalPlugins)
            .add_plugins(bevy::transform::TransformPlugin)
            .add_plugins(bevy::asset::AssetPlugin::default())
            .add_plugins(PhysicsPlugins::default())
            .add_plugins(AircraftFdmPlugin::default());
        app.insert_resource(TimeUpdateStrategy::ManualDuration(Duration::from_secs_f64(
            1.0 / 60.0,
        )));
        let q = pitch_rate_world_z;
        app.add_systems(Startup, move |mut commands: Commands| {
            let initial_rot = Quat::from_rotation_x(std::f32::consts::FRAC_PI_2);
            let root = j3cub::spawn(
                &mut commands,
                Transform::from_xyz(0.0, 300.0, 0.0).with_rotation(initial_rot),
            );
            commands
                .entity(root)
                .insert(LinearVelocity(Vec3::new(27.0, 0.0, 0.0)))
                // Body pitch rate q maps to world Z due to spawn rotation_x(PI/2).
                .insert(AngularVelocity(Vec3::new(0.0, 0.0, q)));
        });
        app.finish();
        app
    }

    let mut baseline = build_app(0.0);
    let q_rads_f32 = 5.0_f32.to_radians();
    let mut perturbed = build_app(q_rads_f32);

    // Run 5 frames: Avian init + flight_state update + aero forces.
    for _ in 0..5 {
        baseline.update();
    }
    for _ in 0..5 {
        perturbed.update();
    }

    // Read ConstantTorque (total aero torque on the root body, world frame).
    let read_torque = |app: &mut App| -> Vec3 {
        let world = app.world_mut();
        let mut query = world.query::<&ConstantTorque>();
        query
            .iter(&world)
            .next()
            .expect("no ConstantTorque found")
            .0
    };

    let t_base = read_torque(&mut baseline);
    let t_pert = read_torque(&mut perturbed);

    // Body pitch torque = world Z torque (due to spawn rotation).
    // Negative means nose-down restoring moment.
    let delta_mz = (t_pert.z - t_base.z) as f64;

    // Back out Cmq: delta_M = Cmq * (q * c / (2V)) * qbar * S * c
    let q_rad = q_rads_f32 as f64;
    let v = 27.0_f64;
    let rho = 1.19_f64; // ~ISA at 300 m
    let qbar = 0.5 * rho * v * v;
    let s = 16.584_f64;
    let c = 1.6_f64;
    let norm = (q_rad * c / (2.0 * v)) * qbar * s * c;
    let cmq_measured = delta_mz / norm;

    let datcom_cmq = -6.0_f64;

    println!("\n-- Emergent Cmq Measurement --------------------------------");
    println!("  Baseline pitch torque (q=0):     {:.1} N*m", t_base.z);
    println!("  Perturbed pitch torque (q=5d/s): {:.1} N*m", t_pert.z);
    println!("  Delta pitch torque:              {:.1} N*m", delta_mz);
    println!(
        "  Measured Cmq:                    {:.2} /rad",
        cmq_measured
    );
    println!("  Datcom target:                   {:.1} /rad", datcom_cmq);
    println!(
        "  Ratio (measured/Datcom):          {:.2}",
        cmq_measured / datcom_cmq
    );
    println!("------------------------------------------------------------");

    // Cmq should be negative (restoring).
    assert!(
        cmq_measured < 0.0,
        "Cmq should be negative (restoring), got {cmq_measured:.2}"
    );

    // Should be between 1x and 3x the Datcom value (more negative, no downwash lag).
    assert!(
        cmq_measured < datcom_cmq,
        "Cmq ({cmq_measured:.1}) should be more negative than Datcom ({datcom_cmq})"
    );
    assert!(
        cmq_measured > datcom_cmq * 3.0,
        "Cmq ({cmq_measured:.1}) should not exceed 3x Datcom ({:.0})",
        datcom_cmq * 3.0
    );
}

/// Verify the startup validation system detects a deliberately broken zone.
/// We spawn an AeroZone with unsorted Table1D breakpoints and confirm the
/// validation system runs without panicking (it logs warnings).
#[test]
fn startup_validation_catches_bad_zone() {
    let mut app = App::new();
    app.add_plugins(MinimalPlugins)
        .add_plugins(bevy::transform::TransformPlugin)
        .add_plugins(bevy::asset::AssetPlugin::default())
        .add_plugins(PhysicsPlugins::default())
        .add_plugins(AircraftFdmPlugin {
            validate_on_startup: true,
        });

    app.insert_resource(TimeUpdateStrategy::ManualDuration(Duration::from_secs_f64(
        1.0 / 60.0,
    )));

    // Spawn an aircraft root with a broken child zone.
    app.add_systems(Startup, |mut commands: Commands| {
        commands
            .spawn(AircraftCoreBundle {
                transform: Transform::from_xyz(0.0, 100.0, 0.0),
                ..Default::default()
            })
            .with_children(|parent| {
                parent.spawn(AeroZoneBundle {
                    zone: AeroZone {
                        // Deliberately unsorted breakpoints.
                        cl: AeroCoeff::Table1D {
                            breakpoints: vec![0.3, 0.0, -0.3],
                            values: vec![1.0, 0.0, -1.0],
                        },
                        cd: AeroCoeff::Scalar(0.01),
                        area_m2: 2.0,
                        chord_m: 0.5,
                        ..Default::default()
                    },
                    collider: Collider::cuboid(0.5, 2.0, 0.02),
                    ..Default::default()
                });
            });
    });

    app.finish();

    // Run a few frames: PostStartup validation runs after Startup.
    // Should NOT panic, only log warnings.
    for _ in 0..3 {
        app.update();
    }

    // If we got here, validation ran without crashing. The actual warnings
    // are logged via bevy::log and not captured in the test, but the
    // unit tests in aero_coeff.rs verify the validation logic itself.
}
